import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";

import {
  SvgModule,
  IconModule,
  ButtonModule,
  DynamicComponentsModule,
  AccordionModule,
  VideoPlayerModule,
  ToggleModule,
  CheckboxModule,
  RadioModule,
  RadioGroupModule,
  TooltipModule,
  PopupModule,
  FlagModule,
  HeaderOverlayModule,
  TagModule,
  LoaderModule,
  LoaderInlineModule,
  AlertModule,
  InputModule,
  InputInlineModule,
  TextareaModule,
  LayoutModule,
  ModalModule,
  NotificationModule,
  ChartModule,
  IconSelectListModule,
  IconStatusModule,
  SwitcherModule
} from "@ironsrc/fusion-ui";

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    SvgModule,
    IconModule.forRoot({svgOptions: {assetsPath: 'https://supersonicads-a.akamaihd.net/demand'}}),
    ButtonModule,
    DynamicComponentsModule,
    AccordionModule,
    VideoPlayerModule,
    ToggleModule,
    CheckboxModule,
    RadioModule,
    RadioGroupModule,
    TooltipModule,
    PopupModule,
    FlagModule,
    HeaderOverlayModule,
    TagModule,
    LoaderModule,
    LoaderInlineModule,
    AlertModule,
    InputModule,
    InputInlineModule,
    TextareaModule,
    LayoutModule,
    ModalModule,
    NotificationModule,
    ChartModule,
    IconSelectListModule,
    IconStatusModule,
    SwitcherModule
  ],
  exports: [
    SvgModule,
    IconModule,
    ButtonModule,
    DynamicComponentsModule,
    AccordionModule,
    VideoPlayerModule,
    ToggleModule,
    CheckboxModule,
    RadioModule,
    RadioGroupModule,
    TooltipModule,
    PopupModule,
    FlagModule,
    HeaderOverlayModule,
    TagModule,
    LoaderModule,
    LoaderInlineModule,
    AlertModule,
    InputModule,
    InputInlineModule,
    TextareaModule,
    LayoutModule,
    ModalModule,
    NotificationModule,
    ChartModule,
    IconSelectListModule,
    IconStatusModule,
    SwitcherModule
  ]
})
export class ComponentsModule {}
